other/django/mysite/kitchen/urls.py
from django.conf.urls import patterns, url

from kitchen import views

urlpatterns = patterns('kitchen.views',
    #url(r'transaction/$', views.TransactionList.as_view()),
    url(r'^$',                     views.index, name="index"),
    url(r'tree/$',                 views.tree,  name="tree"),
    url(r'item/$',                 views.ItemList.as_view()),
    url(r'inventory/$',            views.inventory,         name='inventory'),
    url(r'shoppinglist/$',         views.shoppinglist_view, name='shoppinglist'),
    url(r'add_recipe/$',           views.add_recipe,        name='add_recipe'),
    url(r'^(?P<recipe_id>\d+)/create_recipe_order/$',   views.create_recipe_order, name='create_recipe_order'),
    url(r'^(?P<recipe_id>\d+)/recipe_edit/$',           views.recipe_edit,         name='recipe_edit'),
    url(r'create_recipe/$',        views.create_recipe,    name='create_recipe'),
    url(r'recipeorder_list/$',     views.recipeorder_list, name='recipeorder_list'),
    url(r'recipe_list/$',          views.recipe_list,      name='recipe_list'),
    url(r'^(?P<recipeorder_id>\d+)/recipeorder_edit/$', views.recipeorder_edit,    name='recipeorder_edit'),
    url(r'ingredient_add',         views.ingredient_add,    name='ingredient_add'),
    url(r'ingredient_create',      views.ingredient_create, name='ingredient_create'),
    url(r'item_selector/$',        views.item_selector,       name='item_selector'),
    url(r'item_selector_final/$',  views.item_selector_final, name='item_selector_final'),
    url(r'item_selector_test/$',   views.item_selector_test, name='item_selector_test'),
    )

other/django/mysite/lit/urls.py
from django.conf.urls import patterns, url

import lit.views

urlpatterns = patterns('',
    #url(r'transaction/$', views.TransactionList.as_view()),
    url(r'^$', lit.views.index, name='index'),
    url(r'^mybib.bib$', lit.views.bib, name='bib'),
    )

other/django/mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    
    url(r'^kitchen/',  include('kitchen.urls',  namespace="kitchen")),
    url(r'^lit/',   include('lit.urls',   namespace="lit")),
    url(r'^wiki/',  include('wiki.urls',  namespace="wiki")),
    url(r'^climb/', include('climb.urls', namespace="climb")),
    url(r'^admin/', include(admin.site.urls)),
)

other/django/mysite/kitchen/models.py
from django.db import models

# Create your models here.

class MeasurementType(models.Model):
    name = models.CharField(max_length=256)
    def __unicode__(self):
        return self.name

class Unit(models.Model):
    name = models.CharField(max_length=256)
    measurementtype = models.ForeignKey(MeasurementType)
    
    convert = models.FloatField(null=True)
    
    def __unicode__(self):
        return self.name

#class CategoryBase(models.Model):
#    class Meta:
#        #abstract = True
#        pass

#class CategoryRelation(models.Model):
#    parent = models.ForeignKey(CategoryBase,related_name='+')
#    child  = models.ForeignKey(CategoryBase,related_name='+')

#class Category(CategoryBase):
class Category(models.Model):
    name   = models.CharField(max_length=256)
    #parent = models.ForeignKey(Category, null=True)

    class Meta:
        ordering = ('name',)

    def __unicode__(self):
        return self.name

class CategoryRelation(models.Model):
    parent = models.ForeignKey(Category,related_name='+')
    child  = models.ForeignKey(Category,related_name='+')

    def __unicode__(self):
        return self.parent.name + " --- " + self.child.name
   

class Item(models.Model):

    name = models.CharField(max_length=256)
    unit = models.ForeignKey(Unit, null=True)

    category = models.ForeignKey(Category, null=True)
    price  = models.FloatField(null=True)

    def __unicode__(self):
        #return "Item:" + self.name
        return self.name

    def get_category(self):
        
        c = self.category

        while True:
            lst_cr = CategoryRelation.objects.filter(child = c)
            
            if not lst_cr:
                return c
            else:
                c = lst_cr[0].parent

    class Meta:
        ordering = ('name',)

class Recipe(models.Model):
    name = models.CharField(max_length=256)
    source = models.CharField(max_length=256, blank=True)
    lcm = models.FloatField(default=1.0)
    ingredients = models.ManyToManyField(Item, through='Ingredient')
    text = models.TextField(blank=True)

    class Meta:
        ordering = ('name',)

    def __unicode__(self):
        return "Recipe:" + self.name
    def can_make(self, a, ir_dict):
        #print("can_make")
        #print(ir_dict)

        ings = Ingredient.objects.filter(recipe=self, amount__gt=0)
        
        #print(ings)

        for ing in ings:
            need = a * ing.amount_std

            if not ing.item in ir_dict:
                if need > 0:
                    return False

            ir = ir_dict[ing.item]
            
            if ir < need:
                return False

        return True

class RecipeOrder(models.Model):

    PLANNED  = '0'
    COMPLETE = '1'
    CANCELED = '2'
    STATUS_CHOICES = (
        (PLANNED,  'planned'),
        (COMPLETE, 'complete'),
        (CANCELED, 'canceled'),
        )
                        
    recipe = models.ForeignKey(Recipe)
    amount = models.FloatField()
    status = models.CharField(max_length=1,
        choices=STATUS_CHOICES,
        default=PLANNED)

    def __unicode__(self):
        return self.recipe.name + ": " + str(self.amount)

class Ingredient(models.Model):
    recipe = models.ForeignKey(Recipe)
    item = models.ForeignKey(Item)
    unit = models.ForeignKey(Unit)
    amount = models.FloatField()
    optional = models.BooleanField(default=False)
    def __unicode__(self):
        return self.recipe.name + ": " + self.item.name
    def _get_amount_std(self):
        return self.amount * self.unit.convert
    amount_std = property(_get_amount_std)
    
class RecipeOrderTransaction(models.Model):
    recipeorder = models.ForeignKey(RecipeOrder)
    ingredient  = models.ForeignKey(Ingredient)
    unit        = models.ForeignKey(Unit)
    amount      = models.FloatField()

    def _get_amount_std(self):
        return self.amount * self.unit.convert

    amount_std = property(_get_amount_std)

class Transaction(models.Model):
    item   = models.ForeignKey(Item)
    unit   = models.ForeignKey(Unit)
    amount = models.FloatField()
    def __unicode__(self):
        return self.item.name + ":" + str(self.amount_std)
    def _get_amount_std(self):
        return self.amount * self.unit.convert
    amount_std = property(_get_amount_std)

class Store(models.Model):
    name = models.CharField(max_length=256)
    categories = models.ManyToManyField(Category, through='StoreCategory')
 
    def __unicode__(self):
        return self.name
   
class StoreCategory(models.Model):
    store    = models.ForeignKey(Store)
    category = models.ForeignKey(Category)
    order    = models.FloatField()

    class Meta:
        ordering = ('order',)
    

other/django/mysite/kitchen/forms.py
import django.forms

import kitchen.models

class add_recipe(django.forms.Form):
    name   = django.forms.CharField(max_length=256)
    source = django.forms.CharField(max_length=256)
    lcm    = django.forms.FloatField()
    #ingredients = models.ManyToManyField(Item, through='Ingredient')
    #text   = django.forms.TextField()

class ingredient_add(django.forms.Form):
    unit   = django.forms.ModelChoiceField(queryset=kitchen.models.Unit.objects.all())
    amount = django.forms.DecimalField()

other/django/mysite/kitchen/views.py
import math
import itertools

from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.shortcuts import get_object_or_404, HttpResponseRedirect, HttpResponse
import django.db.models
import django.views.generic

from kitchen.models import *

import kitchen.graph
import kitchen.forms
import kitchen.funcs
import kitchen.classes

def shoppinglist(store_id = None):

    G = kitchen.graph.IngGraph()
    
    dlist = list(kitchen.funcs.demand_list())
    
    ir_dict = dict((item, ir) for item, ir in kitchen.funcs.ir_list())
    
    for item, ir, d in dlist:
        
        # d = amount in item.unit units

        amount = d / item.unit.convert

        if item.price:
            price = amount * item.price
        else:
            price = 0

        #in_e = G.G.in_edges(item, data=True)

        recipes = list(kitchen.funcs.test_in(G, item, d, ir_dict))
        
        cat = kitchen.funcs.category_top_for(item.category)
        
        try:
            store = kitchen.models.Store.objects.get(pk=store_id)
            storecat = kitchen.models.StoreCategory.objects.filter(store=store, category=cat)
            try:
                order = storecat[0].order
            except:
                order = 100000000
        except:
            order = 100000000
        
        #yield item, d / item.unit.convert, item.unit, cat, recipes, order
        yield kitchen.classes.shoppinglist_data(
                item,
                d / item.unit.convert,
                item.unit,
                cat,
                recipes,
                order,
                price)

class ItemList(django.views.generic.ListView):
    
    def get_queryset(self):
        return Item.objects.all()

def inventory(request):

    context = {'items': list(kitchen.funcs.inventory())}
    
    return render(request, 'kitchen/inventory.html', context)

def sum(lst, f):
    ret = 0
    for l in lst:
        ret += f(l)
    return ret

def shoppinglist_view(request):

    try:
        store_id = request.POST['store_id']
    except:
        store_id = None

    items = sorted(list(shoppinglist(store_id)), key = lambda x: x.order)
    
    a = -1
    c = None
    for i in items:
        if i.cat != c:
            a = (a+1) % 6
            c = i.cat

        i.color = "color{}".format(a)

    context = {
            'items':  items,
            'stores': kitchen.models.Store.objects.all(),
            'store_id': store_id,
            'price_sum': sum(items, lambda i: i.price),
            }
    
    return render(request, 'kitchen/shoppinglist.html', context)

def recipeorder_list(request):
    recipeorders = kitchen.models.RecipeOrder.objects.filter(status=kitchen.models.RecipeOrder.PLANNED)
    return render(request, 'kitchen/recipeorder_list.html', {'recipeorders':recipeorders})

def recipe_list(request):
    recipes = Recipe.objects.all()
    return render(request, 'kitchen/recipe_list.html', {'recipes':recipes})

def recipe_edit(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=int(recipe_id))
    return render(request, 'kitchen/recipe_edit.html', {
        'recipe':      recipe,
        'ingredients': Ingredient.objects.filter(recipe=recipe),
        })

# create a new recipe
def create_recipe(request):

    try:
        name = request.POST['name']
    except KeyError:
        return render(request, 'kitchen/error.html', {'message':'create recipe: KeyError'})
    else:
        r = Recipe()
        r.name = name
        r.save()
        
        #return render(request, 'kitchen/error.html', {'message':'create recipe: Success'})
        #return recipe_edit(request, r.id)
        #return HttpResponse('/django/admin/')
        return HttpResponseRedirect("/site2/kitchen/{}/recipe_edit/".format(r.id))

def ingredient_create(request):
    
    try:
        recipe_id = request.POST['recipe_id']
        item_id   = request.POST['item_id']
        unit_id   = request.POST['unit']
        amount    = request.POST['amount']
    except KeyError:
        return render(request, 'kitchen/error.html', {'message':'create recipe: KeyError'})
    else:
        recipe = get_object_or_404(Recipe, pk=int(recipe_id))
        item   = get_object_or_404(Item,   pk=int(item_id))
        unit   = get_object_or_404(Unit,   pk=int(unit_id))
        
        i = Ingredient()
        
        i.recipe = recipe
        i.item = item
        i.unit = unit
        i.amount = amount

        i.save()

        return HttpResponseRedirect("/site2/kitchen/{}/recipe_edit/".format(recipe_id))

def create_recipe_order(request, recipe_id):
    
    r = get_object_or_404(Recipe, pk=recipe_id)

    try:
        amount = request.POST['amount']
    except KeyError:
        return render(request, 'kitchen/shoppinglist.html', {'items':[]})
    else:
        ro = RecipeOrder()
        ro.recipe = r
        ro.amount = amount
        ro.save()

        return HttpResponseRedirect(reverse('kitchen:shoppinglist_view'))
    
def create_transaction(request, item_id):
    
    item = get_object_or_404(Item, pk=item_id)
    
    try:
        amount = request.POST['amount']
    except KeyError:
        return render(request, 'kitchen/shoppinglist.html', {'items':[]})
    else:
        t = Transaction()
        t.item = item
        t.amount = amount
	t.unit = item.unit
        t.save()

        return HttpResponseRedirect(reverse('kitchen:shoppinglist_view'))

def add_recipe(request):
    if request.method == 'POST':
        form = kitchen.forms.add_recipe(request.POST)
        if form.is_valid():
            return HttpResponseRedirect('/admin/')
    else:
        form = kitchen.forms.add_recipe()

    return render(request, 'kitchen/add_recipe.html', {'form':form})

def index(request):
    return render(request, 'kitchen/index.html', {})

def item_selector_final(request):
 
    # pass through
    pass_through = []
    for p in request.POST.items():
        if p[0][0:3] == 'ud_':
            pass_through.append(p)
   
    cat_name = request.POST['cat']

    action = request.POST['ud_action']

    cat = kitchen.models.Category.objects.get(name=cat_name)

    items = Item.objects.filter(category=cat)

    context = {
            'choices': items,
            'action': action, #'kitchen:item_selector_test',
            'pass_through': pass_through,
    }
    
    temp = 'kitchen/item_selector_final_1.html'

    return render(request, temp, context)

def item_selector(request):

    # pass through
    pass_through = []
    for p in request.POST.items():
        if p[0][0:3] == 'ud_':
            pass_through.append(p)

    try:
        cat = request.POST['cat']
    except KeyError:
        cat = None
        #return render(request, 'kitchen/error.html', {'message':'item selector: KeyError'})
    
    #tree = kitchen.funcs.item_selector_tree(selections)

    tree = kitchen.funcs.item_selector_tree2(cat)
    
    context = {
            'cat': cat,
            'pass_through': pass_through,#request.POST.items(),
            'extra': pass_through,#request.POST.items(),
            }
    
    #if isinstance(tree, list):
    if not tree:

        return item_selector_final(request)


        if not cat:
            return render(request, 'kitchen/error.html', {'message':'item selector: no category'})

        choices = kitchen.funcs.category_get_items(cat)
        context['action'] = 'kitchen:item_selector_test'
        temp = 'kitchen/item_selector_final_0.html'
    else:
        choices = tree
        temp = 'kitchen/item_selector.html'

    context['choices'] = choices

    return render(request, temp, context)

  

def item_selector_test(request):
    name = request.POST['name']
    return HttpResponse("you selected item: {}".format(name))

def item_list(request):
    items = kitchen.funcs.item_list()
    context = {'items':items}
    return render(request, 'kitchen/item_list.html', context)

def ingredient_add(request):

    recipe_id = request.POST['ud_recipe_id']

    item_id = request.POST['item_id']

    form = kitchen.forms.ingredient_add(request.POST)

    context = {
            'form':      form,
            'recipe_id': recipe_id,
            'item_id':   item_id,
            }

    return render(request, 'kitchen/ingredient_add.html', context)

def parse_ing_id(s):
    if s[0:4] == "ing_":
        if s[5] == "_":
            return int(s[4])
        elif s[6] == "_":
            return int(s[4:5])
        else:
            return None
    else:
        return None

def recipeorder_edit(request, recipeorder_id):
    recipeorder = get_object_or_404(RecipeOrder, pk=recipeorder_id)

    try:
        request.POST['btnComplete']
    except:
        pass
    else:
        ings = {}
        for k,v in request.POST.items():
            pass
            #if 
            #    ings[int(k[])]


    context = {
            'recipeorder': recipeorder,
            'ingredients': kitchen.models.Ingredient.objects.filter(recipe=recipeorder.recipe),
            'units':       kitchen.models.Unit.objects.all(),
            'ings':        ings,
            }
    return render(request, "kitchen/recipeorder_edit.html", context)

def tree(request):
    
    c_lst = Category.objects.all()

    cr_lst = CategoryRelation.objects.all()

    c_lst_0 = []

    for c in c_lst:
        if not kitchen.funcs.category_is_child(c):
            c_lst_0.append((
                c,
                kitchen.funcs.category_get_children(c),
                Item.objects.filter(category=c)
                ))

    context = {'c_lst_0': c_lst_0}

    return render(request, 'kitchen/tree.html', context)

other/django/mysite/kitchen/templates/kitchen/add_recipe.html
<table>
<form action="/django/kitchen/create_recipe/" method="post">
	{% csrf_token %}
	{{ form }}
	<input type="submit" value="Submit" />
</form>
</table>

other/django/mysite/kitchen/templates/kitchen/error.html
{{ message }}

other/django/mysite/kitchen/templates/kitchen/index.html
<body>
	<h1>Kitchen Database</h1>
	<a href="shoppinglist">shopping list</a><br>
	<a href="recipe_list">recipe list</a><br>
	<a href="recipeorder_list">recipeorder list</a><br>
	<a href="add_recipe">add recipe</a>
</body>

other/django/mysite/kitchen/templates/kitchen/inventory.html
<table>
{% for item, a, gpr in items %}
<tr>
	<td>{{ item }}</td>
	<td>{{ a }}</td>
	<td>
	<table>
		{% for g in gpr %}
			<tr><td>{{ g }}</td></tr>
		{% endfor %}
	</table>
	</td>
</tr>
{% endfor %}
</table>

other/django/mysite/kitchen/templates/kitchen/item_list.html
{#{% extends "base.html" %}#}

{% block content %}
<h2>Items</h2>
<table>
{% for item in object_list %}
	<tr>
		<td>{{ item.name }}</td>
		<td>{{ item.get_category }}</td>
	</tr>
{% empty %}
{% endfor %}
</table>
{% endblock %}

other/django/mysite/kitchen/templates/kitchen/item_selector_final_0.html
<html>
	{% for c in choices %}
	<form action="{% url 'kitchen:item_selector_final' %}" method="post">
		{% csrf_token %}
		<!-- pass_through -->
		{% for p0,p1 in pass_through %}
			<input type="hidden" name="{{ p0 }}" value="{{ p1 }}"/>
		{% endfor %}
		<!---->
		<input type="hidden" name="name" value="{{ c }}"/>
		<input type="submit" value="{{ c }}">
	</form>
	{% endfor %}
</html>

other/django/mysite/kitchen/templates/kitchen/item_selector_final_1.html
<html>
	{% for c in choices %}
	<form action="{% url action %}" method="post">
		{% csrf_token %}
		<!-- pass_through -->
		{% for p0,p1 in pass_through %}
			<input type="hidden" name="{{ p0 }}" value="{{ p1 }}"/>
		{% endfor %}
		<!---->
		<input type="hidden" name="name" value="{{ c }}"/>
		<input type="hidden" name="item_id" value="{{ c.id }}"/>
		<input type="submit" value="{{ c }}">
	</form>
	{% endfor %}
</html>

other/django/mysite/kitchen/templates/kitchen/recipe_edit.html
<html>
	<head>
		<style>
			table, td {
				border: 1px solid black;
			}
			.left {
				float: left;
				width: 200px;
			}
			.center {
				float: left;
			}
		</style>
	</head>
	<body>
		<div class="left">
			<a href="../../">kitchen</a><br>
			<a href="../../../admin/kitchen">kitchen admin</a>
		</div>
		<div class="center">
			<h1>recipe</h1>
			<h2>{{ recipe.name }}</h2>
			<table>
				{% for ing in ingredients %}
				<tr>
					<td><a href="../../../admin/kitchen/item/{{ing.item.id}}/">{{ ing.item.name }}</a></td>
					<td>{{ ing.unit }}</td>
					<td>{{ ing.amount }}</td>
				</tr>
				{% endfor %}
			</table>
			<form action="{% url 'kitchen:item_selector' %}" method="post">
				{% csrf_token %}
				<input type="hidden" name="ud_action" value="kitchen:ingredient_add"/>
				<input type="hidden" name="ud_recipe_id" value="{{ recipe.id }}"/>
				<input type="submit" value="add item"/>
			</form>
		</div>
	</body>
</html>

other/django/mysite/kitchen/templates/kitchen/recipe_list.html
<html>
{% extends "kitchen/base.html" %}

{% block style %}
form {
	margin:0px;
}
{% endblock %}

{% block content %}
<table>
{% for r in recipes %}
<tr>
	<td>{{ r.name }}</td>
	<td>
		<form action="{% url 'kitchen:recipe_edit' r.id %}" method="post">
			{% csrf_token %}
			<input type="submit" value="edit">
		</form>
	</td>
</tr>
{% endfor %}
</table>
{% endblock %}

other/django/mysite/kitchen/templates/kitchen/recipeorder_edit.html
<html>
	<head>
		<style>
			table, td {
				border: 1px solid black;
				border-collapse: collapse;
			}
			td {
				padding: 3px;
			}
		</style>
	</head>
	<body>
		{{ recipeorder.status }}
		<form action="{% url 'kitchen:recipeorder_edit' recipeorder.id %}" method="post" id="form">
		{% csrf_token %}
		<table>
			{% for ing in ingredients %}
			<tr>
				<td>{{ ing.item.name }}</td>
				<td>{{ ing.unit.name }}</td>
				<td>{{ ing.amount }}</td>
				<td>
					<select name="ing_{{ ing.id }}_unit_id" form="form">
						{% for unit in units %}
						<option value="{{ unit.id }}" {% if unit == ing.unit %}selected{% endif %}>{{ unit.name }}</option>
						{% endfor %}
					</select>
				</td>
				<td><input type="number" name="ing_{{ ing.id }}_amount" value="{{ ing.amount }}"></td>
			</tr>
			{% endfor %}
		</table>
		<input type="submit" name="btnComplete" value="complete">
		</form>

		{{ ings }}
	</body>
</html>

other/django/mysite/kitchen/templates/kitchen/recipeorder_list.html
{% extends "kitchen/base.html" %}

{% block content %}
<table>
{% for ro in recipeorders %}
<tr>
	<td>{{ ro.recipe.name }}</td>
	<td>
		<form action="{% url 'kitchen:recipeorder_edit' ro.id %}" method="post">
			{% csrf_token %}
			<input type="submit" value="edit">
		</form>
	</td>
</tr>
{% endfor %}
</table>
{% endblock %}

other/django/mysite/kitchen/templates/kitchen/shoppinglist.html
{% extends "kitchen/base.html" %}

{% load staticfiles %}

{% block style %}
	.color0 { background-color: #ffcccc; }
	.color1 { background-color: #ffddbb; }
	.color2 { background-color: #ffffcc; }
	.color3 { background-color: #ccffcc; }
	.color4 { background-color: #C0E0FF; }
	.color5 { background-color: #ffccff; }
{% endblock %}

{% block content %}
	<form action="{% url 'kitchen:shoppinglist' %}" method="post" id="select_store">
		{% csrf_token %}
		<input type="submit" value="select">
	</form>

	<select name="store_id" form="select_store">
		{% for store in stores %}
		<option value="{{ store.id }}">{{ store.name }}</option>
		{% endfor %}
	</select>

	<table>
	<tr>
		<th></th>
		<th>Item</th>
		<th>Amount</th>
		<th>Unit</th>
		<th>Category</th>
		<th>Price</th>
	</tr>
	{% for item in items %}
	<tr class="{{ item.color }}">
		<td><input type="checkbox"/></td>
		<td><a href="../../admin/kitchen/item/{{ item.item.id }}/">{{ item.item.name }}</a></td>
		<td>{{ item.amount }}</td>
		<td>{{ item.unit }}</td>
		<td class="{{ c }}">{{ item.cat }}</td>
		<td>{{ item.price }}</td>
		{% if item.recipes %}
		<td><table>
			{% for rec, a, can in item.recipes %}
			<form action="{% url 'kitchen:create_recipe_order' rec.id %}" method="post">
				{% csrf_token %}
				<tr>
					<td>{{ rec }}</td>
					<td>{{ a }}</td>
					<td><input type="submit" value="Create"/></td>
				</tr>
				<input type="hidden" name="amount" value="{{ a }}"/>
			</form>
			{% endfor %}
		</table></td>
		{% endif %}
	</tr>
	{% endfor %}
	</table>

	{{ price_sum }}	
	
{% endblock %}

other/django/mysite/kitchen/templates/kitchen/transaction_list.html
{#{% extends "base.html" %}#}

{% block content %}
<h2>Publishers</h2>
<ul>
{% for transaction in object_list %}
<li>{{ transaction.item.name }}</li>
{% endfor %}
</ul>
{% endblock %}

other/django/mysite/kitchen/templates/kitchen/tree_items.html
<td>
	<table>
		{% for item in items %}
		<tr>
			<td class="item">
				<!--<form action="/django/admin/kitchen/item/{{ item.id }}/" method="post">
					{% csrf_token %}
					<input type="submit" value="{{ item.name }}"></input>
				</form>-->
				<a href="/site2/admin/kitchen/item/{{ item.id }}/">{{ item.name }}</a>
			</td>
		</tr>
		{% endfor %}
	</table>
</td>