other/django/mysite/climb/urls.py
from django.conf.urls import patterns, url

from climb import views

urlpatterns = patterns('climb.views',
    url(r'^$',                    views.index,           name="index"),
    url(r'location_list/$',       views.location_list,   name='location_list'),
    url(r'area_list/$',           views.area_list,       name='area_list'),
    url(r'wall_list/$',           views.wall_list,       name='wall_list'),
    url(r'route_list/$',          views.route_list,      name='route_list'),
    url(r'route_create/$',        views.route_create,    name='route_create'),
    url(r'pitch_list/$',          views.pitch_list,      name='pitch_list'),
    url(r'climb_create/$',        views.climb_create,    name='climb_create'),
    )

other/django/mysite/lit/urls.py
from django.conf.urls import patterns, url

import lit.views

urlpatterns = patterns('',
    #url(r'transaction/$', views.TransactionList.as_view()),
    url(r'^$', lit.views.index, name='index'),
    url(r'^mybib.bib$', lit.views.bib, name='bib'),
    )

other/django/mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    
    url(r'^kitchen/',  include('kitchen.urls',  namespace="kitchen")),
    url(r'^lit/',   include('lit.urls',   namespace="lit")),
    url(r'^wiki/',  include('wiki.urls',  namespace="wiki")),
    url(r'^climb/', include('climb.urls', namespace="climb")),
    url(r'^admin/', include(admin.site.urls)),
)

other/django/mysite/climb/models.py
from django.db import models

# Create your models here.

class Location(models.Model):
    name     = models.CharField(max_length=256)

    def __unicode__(self):
        return self.name

class Area(models.Model):
    name     = models.CharField(max_length=256)
    location = models.ForeignKey(Location)
    
    def __unicode__(self):
        return self.name

class Wall(models.Model):
    name     = models.CharField(max_length=256)
    area     = models.ForeignKey(Area)
    
    def __unicode__(self):
        return self.name

class Route(models.Model):
    name     = models.CharField(max_length=256)
    wall     = models.ForeignKey(Wall)
    
    def __unicode__(self):
        return self.name

class Pitch(models.Model):
    name     = models.CharField(max_length=256)
    route    = models.ForeignKey(Route)

    def __unicode__(self):
        return self.name

class Climb(models.Model):
    date     = models.DateField()
    pitch    = models.ForeignKey(Pitch)

other/django/mysite/climb/forms.py
import django.forms

import climb.models

class route_select(django.forms.Form):
    route = django.forms.ModelChoiceField(
            queryset=climb.models.Route.objects.all())

class pitch_widget(django.forms.Widget):
    """
    Base class for all <input> widgets (except type='checkbox' and
    type='radio', which are special).
    """
    input_type = "text"  # Subclasses must define this.

    def _format_value(self, value):
        if self.is_localized:
            return formats.localize_input(value)
        return value

    def render(self, name, value, attrs=None):
        if value is None:
            value = ''
        final_attrs = self.build_attrs(attrs, type=self.input_type, name=name)
        if value != '':
            # Only add the 'value' attribute if a value is non-empty.
            final_attrs['value'] = force_text(self._format_value(value))

        form = route_select()

        s0 = unicode(route_select.route)
        s1 = django.utils.html.format_html('<input{} />', django.forms.utils.flatatt(final_attrs))

        return s0

class route_create(django.forms.Form):
    name   = django.forms.CharField(max_length=256)
    wall   = django.forms.ModelChoiceField(
            queryset=climb.models.Wall.objects.all())
   
class climb_create(django.forms.Form):
    date   = django.forms.DateField()

    location = django.forms.ModelChoiceField(
            queryset=climb.models.Location.objects.all())
    area     = django.forms.ModelChoiceField(
            queryset=climb.models.Area.objects.all())
    wall     = django.forms.ModelChoiceField(
            queryset=climb.models.Wall.objects.all())
    route    = django.forms.ModelChoiceField(
            queryset=climb.models.Route.objects.all())
    pitch    = django.forms.ModelChoiceField(
            queryset=climb.models.Pitch.objects.all())
    

other/django/mysite/climb/views.py
import django.shortcuts

# Create your views here.

import climb.forms
import climb.models

def index(request):
    return django.shortcuts.render(request, 'climb/index.html', {})

def location_list(request):
    return django.shortcuts.render(
            request,
            'climb/location_list.html',
            {'locations':climb.models.Location.objects.all()})

def area_list(request):
    return django.shortcuts.render(
            request,
            'climb/area_list.html',
            {'areas':climb.models.Area.objects.all()})

def wall_list(request):
    return django.shortcuts.render(
            request,
            'climb/wall_list.html',
            {'walls':climb.models.Wall.objects.all()})

def route_list(request):
    return django.shortcuts.render(
            request,
            'climb/route_list.html',
            {'routes':climb.models.Route.objects.all()})

def route_create(request):
    if request.method == 'POST':
        form = climb.forms.route_create(request.POST)
        if form.is_valid():
            r = climb.models.Route()
            r.name     = form.cleaned_data['name']
            r.location = form.cleaned_data['location']
            r.area     = form.cleaned_data['area']
            r.wall     = form.cleaned_data['wall']
            r.save()

            return django.shortcuts.HttpResponseRedirect('/django/admin/climb/')
    else:
        form = climb.forms.route_create()

    return django.shortcuts.render(request, 'climb/route_create.html', {'form':form})

def pitch_list(request):
    return django.shortcuts.render(
            request,
            'climb/pitch_list.html',
            {'pitches':climb.models.Pitch.objects.all()})

    
    
def set_qs_0(form, a, b, c):
    #def set_qs_0(form, name_0, model0, name0, model_1, i, q):

    #print name_0, model0, name0, model_1, i

    if not b:
        c.q = c.model.objects.all()
        return None

    #i = form[name0].value()

    if not b.v:
        c.q = c.model.objects.none()
        c.v = None
        return None
    
    m0 = b.model.objects.get(pk=b.v)
    
    print "m0 = ",m0.id,m0.name
    
    if b:
        #if not (m0 in form.fields[name_0].queryset):
        if not (m0 in b.q):
            print "mismatch"
            c.q = c.model.objects.none()
            return None
    
    c.q = c.model.objects.filter(**{b.name:m0})

    if len(c.q) == 1:
        c.v = c.q[0].id

    

class myfield():
    def __init__(self, name, model):
        self.name = name
        self.model = model

def climb_create(request):
    if request.method == 'POST':
        form = climb.forms.climb_create(request.POST)
        if form.is_valid():
            c = climb.models.Climb()
            c.date  = form.date
            c.pitch = form.pitch
            c.save()

            return django.shortcuts.HttpResponseRedirect('/django/admin/climb/')
    else:
        form = climb.forms.climb_create()

    p=[
            None,
            None,
            myfield('location', climb.models.Location),
            myfield('area', climb.models.Area),
            myfield('wall', climb.models.Wall),
            myfield('route', climb.models.Route),
            myfield('pitch', climb.models.Pitch)]
    
    names = list(a.name for a in p[2:])
   
    for a in p[2:]:
        a.v = form[a.name].value()

    for ind in range(len(p))[2:]:

        print "ind",ind

        # temp is the queryset for field at ind

        temp = set_qs_0(
                form,
                p[ind-2],
                p[ind-1],
                p[ind-0]
                )
        
        #print a[1],b[1],c[1]
        print "quertyset ="
        print "\n".join("  {0} {1}".format(o.id,o.name) for o in p[ind].q)

    ini = dict([ (a.name, a.v) for a in p[2:] ])

    print ini

    form1 = climb.forms.climb_create(initial=ini)

    for a in p[2:]:
        form1.fields[a.name].queryset = a.q

    return django.shortcuts.render(request, 'climb/climb_create.html', {'form':form1})

other/django/mysite/climb/templates/climb/area_list.html
<table>
	<tr><th>Location</th><th>Area</th></tr>
	{% for a in areas %}
	<tr><td>{{ a.location.name }}</td><td>{{ a.name }}</td></tr>
	{% endfor %}
</table>

other/django/mysite/climb/templates/climb/climb_create.html
<html>
<head>
	<script src="https://code.jquery.com/jquery-1.10.2.js"></script>
</head>

<body>
<table>
	<form action="{% url 'climb:climb_create' %}" method="post">
		{% csrf_token %}
		{{ form }}
		<input type="submit" value="Submit" />
	</form>
</table>
</body>

<script>
	$("#id_location").change(function(){
		$("form").submit();
	});
	$("#id_area").change(function(){
		$("form").submit();
	});
	$("#id_wall").change(function(){
		$("form").submit();
	});
	$("#id_route").change(function(){
		$("form").submit();
	});
</script>
</html>

other/django/mysite/climb/templates/climb/index.html
<h2>Locations</h2>
<a href="location_list">list</a>

<h2>Areas</h2>
<a href="area_list">list</a>

<h2>Walls</h2>
<a href="wall_list">list</a>

<h2>Routes</h2>
<a href="route_list">list</a><br>
<a href="route_create">create</a>

<h2>Pitches</h2>
<a href="pitch_list">list</a><br>

<h2>Climbs</h2>
<a href="climb_create">create</a>

other/django/mysite/climb/templates/climb/location_list.html
<table>
	{% for l in locations %}
	<tr><td>{{ l.name }}</td></tr>
	{% endfor %}
</table>

other/django/mysite/climb/templates/climb/pitch_list.html
<table>
	<tr><th>Location</th><th>Area</th><th>Wall</th><th>Route</th><th>Pitch</th></tr>
	{% for p in pitches %}
	<tr>
		<td>{{ p.route.wall.area.location.name }}</td>
		<td>{{ p.route.wall.area.name }}</td>
		<td>{{ p.route.wall.name }}</td>
		<td>{{ p.route.name }}</td>
		<td>{{ p.name }}</td>
	</tr>
	{% endfor %}
</table>

other/django/mysite/climb/templates/climb/route_create.html
<table>
<form action="/django/climb/route_create/" method="post">
	{% csrf_token %}
	{{ form }}
	<input type="submit" value="Submit" />
</form>
</table>

other/django/mysite/climb/templates/climb/route_list.html
<table>
	<tr><th>Location</th><th>Area</th><th>Wall</th><th>Route</th></tr>
	{% for r in routes %}
	<tr>
		<td>{{ r.wall.area.location.name }}</td>
		<td>{{ r.wall.area.name }}</td>
		<td>{{ r.wall.name }}</td>
		<td>{{ r.name }}</td>
	</tr>
	{% endfor %}
</table>

other/django/mysite/climb/templates/climb/wall_list.html
<table>
	{% for w in walls %}
	<tr><td>{{ w.area.location.name }}</td><td>{{ w.area.name }}</td><td>{{ w.name }}</td></tr>
	{% endfor %}
</table>